import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
// import { useAuthStore } from '../../store/authStore';
import api from '../../utils/api';
import LoadingSpinner from '../../components/UI/LoadingSpinner';

const ComplianceReport = () => {
  const { batchId } = useParams();
  // const { user } = useAuthStore();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const response = await api.get(`/compliance/report/${batchId}`);
        setReport(response.data);
      } catch (err) {
        setError('Failed to fetch compliance report');
      } finally {
        setLoading(false);
      }
    };

    if (batchId) {
      fetchReport();
    }
  }, [batchId]);

  if (loading) return <LoadingSpinner />;
  if (error) return <div className="text-red-500">{error}</div>;
  if (!report) return <div>Report not found</div>;

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold mb-6">Compliance Report - Batch {batchId}</h1>
      
      <div className="bg-white rounded-lg shadow-md p-6 mb-6">
        <h2 className="text-lg font-semibold mb-4">Summary</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <p><strong>Overall Status:</strong> 
              <span className={`ml-2 px-2 py-1 rounded text-sm ${
                report.overallStatus === 'compliant' ? 'bg-green-100 text-green-800' :
                report.overallStatus === 'warning' ? 'bg-yellow-100 text-yellow-800' :
                'bg-red-100 text-red-800'
              }`}>
                {report.overallStatus}
              </span>
            </p>
            <p><strong>Compliance Score:</strong> {report.complianceScore}%</p>
            <p><strong>Total Checks:</strong> {report.totalChecks}</p>
            <p><strong>Passed Checks:</strong> {report.passedChecks}</p>
            <p><strong>Failed Checks:</strong> {report.failedChecks}</p>
          </div>
          <div>
            <p><strong>Report Generated:</strong> {new Date(report.generatedAt).toLocaleString()}</p>
            <p><strong>Generated By:</strong> {report.generatedBy}</p>
            <p><strong>Batch Status:</strong> {report.batchStatus}</p>
          </div>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-lg font-semibold mb-4">Detailed Checks</h2>
        <div className="space-y-4">
          {report.checks?.map((check, index) => (
            <div key={index} className="border border-gray-200 rounded-lg p-4">
              <div className="flex justify-between items-start mb-2">
                <h3 className="font-semibold">{check.name}</h3>
                <span className={`px-2 py-1 rounded text-sm ${
                  check.status === 'pass' ? 'bg-green-100 text-green-800' :
                  check.status === 'warning' ? 'bg-yellow-100 text-yellow-800' :
                  'bg-red-100 text-red-800'
                }`}>
                  {check.status}
                </span>
              </div>
              <p className="text-gray-600 mb-2">{check.description}</p>
              {check.details && (
                <div className="text-sm text-gray-500">
                  <strong>Details:</strong> {check.details}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default ComplianceReport;
